version: "3"

dotenv:
  - ".env"

tasks:
  leaderboard:
    desc: "Show AOC private leaderboard"
    preconditions:
      - sh: "[ {{.SESSION}} ]"
        msg: "SESSION env var is not set. Get session cookie value from your browser."
      - sh: "[ {{.LEADERBOARD_ID}} ]"
        msg: "LEADERBOARD_ID env var is not set."
    cmds:
      - python leaderboard.py

  download:
    desc: "Download input for the day"
    dir: ./day{{.DAY}}
    preconditions:
      - sh: "[ {{.DAY}} ]"
        msg: "DAY env var is not set."
    status:
      - test -s "input.txt"
      - test -s "test.txt"
    vars:
      ADD_TITLE: "{{ .TITLE | default 0 }}"
    cmds:
      - curl -f --cookie "session={{.SESSION}}" https://adventofcode.com/2022/day/{{.DAY}}/input -o input.txt
      - curl -f --cookie "session={{.SESSION}}" https://adventofcode.com/2022/day/{{.DAY}} -o {{.DAY}}.html
      - defer: rm {{.DAY}}.html
      - cmd: |
          python -c "
          from bs4 import BeautifulSoup as BS
          from pathlib import Path

          test_input_file = Path('test.txt')
          main_file = Path('main.py')
          html_file = Path('{{.DAY}}.html')
          soup = BS(html_file.read_text())

          # title
          title = soup.select('.day-desc > h2')[0].text
          print(title)

          # input
          code = soup.select('pre > code')[0].text.rstrip('\n')
          test_input_file.write_text(code)
          print(code)

          if not {{.ADD_TITLE}}:
              exit(0)
          with main_file.open('r+') as file:
              contents = file.read()
              if not contents.startswith('# ---'):
                  file.seek(0)
                  file.write(f'# {title}\n\n')
                  file.write(contents)
          "

  init:
    desc: "Setup project dir for the day"
    preconditions:
      - sh: "[ {{.DAY}} ]"
        msg: "DAY env var is not set."
    status:
      - test -f day{{.DAY}}/__init__.py
    cmds:
      - cp -r template day{{.DAY}}
